### ISSUE TITLE
429 Client Error: UNKNOWN STATUS CODE

### ISSUE THREAD

**Issue by afs2015** [Ossus/appannie#1]
Hey as a heads up I ran into this error attempting to run ./appannie.py after cloning the repo and updating settings.py.

Failed to download:
https://api.appannie.com/v1.2/accounts/private_account_info
429 Client Error: UNKNOWN STATUS CODE
Traceback (most recent call last):
  File "./appannie.py", line 152, in <module>
    main()
  File "./appannie.py", line 58, in main
    sales = _sales(account, app_id)
  File "./appannie.py", line 124, in _sales
    sales.extend(raw['sales_list'])
KeyError: 'sales_list'

**Comment by p2** [comment]
Ha, I had no idea others are using this. I just ran this against my accounts and I did not get the error. And 429 means _too many requests_, so I'm assuming you used this a bit too often while testing, no longer did data back in return and then the error hit. Can you try again later? Meanwhile I'll push a fix to not hardcode this key.

**Comment by afs2015** [comment]
Yep! This is one of the first things that came up when I googled Annie API python. Also you were right about the rate limiting being the culprit.

It now doesn't give a key error but continues to fail on the rate limit:
`failed to download:
https://api.appannie.com/v1.2/apps/ios/app/fake_id/reviews?break_down=date
429 Client Error: UNKNOWN STATUS CODE
Failed to download:
https://api.appannie.com/v1.2/accounts/fake_id/products/fake_id/sales?break_down=date
429 Client Error: UNKNOWN STATUS CODE`

I'll probably write a feature to add an option in settings to add a time delay in between requests for someone like myself who will hit the 30 max calls per minute limit.

**Comment by p2** [comment]
Ah, you're hitting this by running the script once because you have so many accounts/apps? Hadn't thought that that might become an issue. :)

**Comment by afs2015** [comment]
Yep, 60+ apps in multiple accounts. It's kind of an usual case I admit.
